name: 'khmer24_car_price'
version: '1.0.0'
config-version: 2

profile: 'khmer24_duckdb'

model-paths:    ["models"]
analysis-paths: ["analyses"]
macro-paths:    ["macros"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
target-path:    "target"
clean-targets:  ["target"]

# Medallion Architecture Materialization
models:
  khmer24_car_price:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
